INSERT INTO CARRO (NOME, MODELO, MARCA) VALUES ('Stilo','Hatch','Fiat');
INSERT INTO CARRO (NOME, MODELO, MARCA) VALUES ('208','Hatch','Peugeot');
INSERT INTO CARRO (NOME, MODELO, MARCA) VALUES ('206','Hatch','Peugeot');